### ISSUE TITLE
Error in `package_file()`: pllittle/smarter is not a directory.

### ISSUE THREAD

**Issue by Noel388** [pllittle/UNMASC#14]
Hi, I receive this error when downloading the UNMASC package,
for this particular step:
```
for(pack in req_packs){
	
	chk_pack = tryCatch(find.package(pack),
		error = function(ee){NULL})
	
	if( !is.null(chk_pack) ){
		library(pack,character.only = TRUE)
		next
	}
	
	if( pack %in% cran_packs ){
		install.packages(pack,dependencies = TRUE)
	} else if( pack %in% bioc_packs ){
		BiocManager::install(pkg = pack,dependencies = TRUE)
	} else if( pack %in% github_packs ){
		devtools::install(sprintf("pllittle/%s",pack),
			dependencies = TRUE)
	}
	
}
```

![image](https://user-images.githubusercontent.com/44961861/219842648-c49fa9b0-b306-4987-8fe2-2f8f7356d49f.png)

thank you!

**Comment by nukaemon** [comment]
I think **devtools::install_github** must be used instead of **devtools::install** but I haven't tried so don't know if this is the correct answer.
My way of avoiding this error is replacing 
```
	} else if( pack %in% github_packs ){
		devtools::install(sprintf("pllittle/%s",pack),
			dependencies = TRUE)**
	}
```
with
```
	} else if( pack %in% github_packs ){
                  remotes::install_github(sprintf("pllittle/%s",pack)
	}
```

Please see [here](https://rdrr.io/github/pllittle/smarter/).
You should have **remotes** package installed in advance.
